dnd_dictionary_pt_en = {
    # Termos Iniciais Fornecidos (mantidos como base)
    'anão': 'dwarf', 'anões': 'dwarves', 'anao': 'dwarf', 'anoes': 'dwarves', 'anãozinho': 'dwarf', 'anõ': 'dwarf',
    'elfo': 'elf', 'elfos': 'elves', 'elfu': 'elf', 'elpho': 'elf', 'elfoz': 'elves',
    'características': 'traits', 'caracteristicas': 'traits', 'caraterísticas': 'traits', 'carateristicas': 'traits',
    'habilidades': 'abilities', 'habilidade': 'ability', 'abilidadi': 'ability', 'habilidadi': 'ability', 'hablidade': 'ability',
    'raça': 'race', 'raças': 'races', 'raca': 'race', 'racas': 'races', 'raçaas': 'races',
    'classe': 'class', 'classes': 'classes', 'clase': 'class', 'clases': 'classes', 'clas': 'class',
    'magia': 'spell', 'magias': 'spells', 'magica': 'magic', 'mágia': 'spell', 'mágica': 'magic', 'majia': 'spell',
    'armadura': 'armor', 'armaduras': 'armors', 'armdura': 'armor', 'armaduraa': 'armor',
    'ataque': 'attack', 'ataques': 'attacks', 'ataq': 'attack', 'atake': 'attack', 'attaque': 'attack',
    'dano': 'damage', 'danos': 'damages', 'dano e cura': 'damage and healing', 'danu': 'damage',
    'resistência': 'resistance', 'resistencias': 'resistances', 'resistencia': 'resistance', 'resistênsia': 'resistance', 'rezistência': 'resistance',

    # Raças e Linhagens (Races & Lineages) - Expansão
    'humano': 'human', 'humanos': 'humans', 'hmano': 'human', 'humanu': 'human',
    'halfling': 'halfling', 'halflings': 'halflings', 'meio-pé': 'halfling', 'meiope': 'halfling', 'halflin': 'halfling',
    'meio-elfo': 'half-elf', 'meio-elfos': 'half-elves', 'meio elfo': 'half-elf', 'meioelfo': 'half-elf', 'mio-elfo': 'half-elf',
    'meio-orc': 'half-orc', 'meio-orcs': 'half-orcs', 'meio orc': 'half-orc', 'meioorc': 'half-orc', 'mio-orc': 'half-orc',
    'gnomo': 'gnome', 'gnomos': 'gnomes', 'nomo': 'gnome', 'gnmo': 'gnome', 'gnomoz': 'gnomes',
    'draconato': 'dragonborn', 'draconatos': 'dragonborn', 'dracnato': 'dragonborn', 'dragonato': 'dragonborn', 'draconatu': 'dragonborn',
    'tiefling': 'tiefling', 'tieflings': 'tieflings', 'tifling': 'tiefling', 'teifling': 'tiefling', 'tieflin': 'tiefling',
    'goliath': 'goliath', 'goliaths': 'goliath', 'golias': 'goliath', 'goliate': 'goliath', 'golia': 'goliath',
    'aasimar': 'aasimar', 'aasimars': 'aasimar', 'asimar': 'aasimar', 'aassimar': 'aasimar', 'aasima': 'aasimar',
    'firbolg': 'firbolg', 'firbolgs': 'firbolg', 'firblog': 'firbolg', 'fribolg': 'firbolg',
    'kenku': 'kenku', 'kenkus': 'kenku', 'kanku': 'kenku', 'kenko': 'kenku',
    'lizardfolk': 'lizardfolk', 'homem-lagarto': 'lizardfolk', 'homem lagarto': 'lizardfolk', 'lizadfolk': 'lizardfolk', 'lagartohomem': 'lizardfolk',
    'tabaxi': 'tabaxi', 'tabaxis': 'tabaxi', 'tabxi': 'tabaxi', 'tabax': 'tabaxi',
    'tritão': 'triton', 'tritões': 'tritons', 'tritao': 'triton', 'tritom': 'triton', 'tritã': 'triton',
    'orc': 'orc', 'orcs': 'orcs', 'ork': 'orc', 'orq': 'orc', 'orcz': 'orcs',
    'goblin': 'goblin', 'goblins': 'goblins', 'goblim': 'goblin', 'gobln': 'goblin', 'gobblin': 'goblin',
    'hobgoblin': 'hobgoblin', 'hobgoblins': 'hobgoblins', 'hobogoblin': 'hobgoblin', 'hobgoblim': 'hobgoblin',
    'bugbear': 'bugbear', 'bugbears': 'bugbear', 'bugbar': 'bugbear', 'bugber': 'bugbear',
    'yuan-ti': 'yuan-ti', 'yuan ti': 'yuan-ti', 'yuant-ti': 'yuan-ti', 'yuan-ti puro-sangue': 'yuan-ti pureblood', 'yuant puro-sangue': 'yuan-ti pureblood',
    'genasi': 'genasi', 'genasis': 'genasi', 'genazi': 'genasi',
    'genasi de ar': 'air genasi', 'genasi de fogo': 'fire genasi', 'genasi de água': 'water genasi', 'genasi de terra': 'earth genasi',
    'warforged': 'warforged', 'forjado de guerra': 'warforged', 'warforge': 'warforged', 'warforg': 'warforged',
    'centauro': 'centaur', 'centauros': 'centaurs', 'centoro': 'centaur',
    'minotauro': 'minotaur', 'minotauros': 'minotaurs', 'minotoro': 'minotaur',
    'changelings': 'changelings', 'mutante': 'changeling', 'trocador': 'changeling', 'changeling': 'changeling',
    'kobold': 'kobold', 'kobolds': 'kobolds', 'cobold': 'kobold', 'kobolde': 'kobold',
    'shifter': 'shifter', 'shifters': 'shifters', 'metamorfo': 'shifter', 'shifte': 'shifter',

    # Classes - Expansão
    'bárbaro': 'barbarian', 'barbaro': 'barbarian', 'barbaru': 'barbarian', 'bárbar': 'barbarian', 'barboro': 'barbarian',
    'bardo': 'bard', 'bardu': 'bard', 'bado': 'bard',
    'bruxo': 'warlock', 'bruxu': 'warlock', 'brxo': 'warlock', 'brux': 'warlock',
    'clérigo': 'cleric', 'clerigo': 'cleric', 'clérgo': 'cleric', 'clergo': 'cleric', 'cleri': 'cleric',
    'druida': 'druid', 'druda': 'druid', 'druída': 'druid', 'druidi': 'druid',
    'feiticeiro': 'sorcerer', 'feitisero': 'sorcerer', 'feiticero': 'sorcerer', 'feitceiro': 'sorcerer', 'feitiçeiro': 'sorcerer',
    'guerreiro': 'fighter', 'gerreiro': 'fighter', 'guereiro': 'fighter', 'guerero': 'fighter', 'guerrero': 'fighter',
    'ladino': 'rogue', 'ladrão': 'rogue', 'ladrao': 'rogue', 'ladin': 'rogue', 'ladrã': 'rogue',
    'mago': 'wizard', 'magu': 'wizard', 'mágo': 'wizard', 'magoo': 'wizard', 'mgo': 'wizard',
    'monge': 'monk', 'mongue': 'monk', 'mônge': 'monk', 'monje': 'monk',
    'paladino': 'paladin', 'paladno': 'paladin', 'paladi': 'paladin', 'paldino': 'paladin',
    'patrulheiro': 'ranger', 'ranger': 'ranger', 'patrulero': 'ranger', 'patruleiro': 'ranger', 'rangr': 'ranger',
    'artífice': 'artificer', 'artifice': 'artificer', 'artifce': 'artificer', 'artíficer': 'artificer', 'artifici': 'artificer',
    'blood hunter': 'blood hunter', 'caçador de sangue': 'blood hunter', 'bloodhunter': 'blood hunter', 'blod hunter': 'blood hunter',
    'psionico': 'psionic', 'psionica': 'psionic', 'psiónico': 'psionic', 'psiônico': 'psionic',

    # Subclasses (Exemplos)
    'caminho do berserker': 'path of the berserker', 'berserker': 'berserker', 'bserker': 'berserker',
    'colégio do conhecimento': 'college of lore', 'colegio do conhecimento': 'college of lore', 'colégio de saber': 'college of lore',
    'pacto do arquifada': 'pact of the archfey', 'pacto da fada': 'pact of the archfey', 'arquifada': 'archfey',
    'domínio da vida': 'life domain', 'dominio da vida': 'life domain', 'domínio de vida': 'life domain',
    'círculo da lua': 'circle of the moon', 'circulo da lua': 'circle of the moon', 'círculo lunar': 'circle of the moon',
    'linhagem dracônica': 'draconic bloodline', 'linhagem draconica': 'draconic bloodline', 'escola de evocação': 'school of evocation',
    'caminho do cavaleiro': 'path of the knight', 'cavaleiro': 'knight', 'caminho de cavaleiro': 'path of the knight',
    'lâmina amaldiçoada': 'hexblade', 'hexblade': 'hexblade', 'lama amaldiçoada': 'hexblade', 'lâmina amaldiçoada': 'oath of devotion', 'juramento de devocao': 'oath of devotion', 'devoção': 'devotion',
    'caminho das sombras': 'way of shadows', 'pathway of shadows': 'caminho das sombras',
    'tradição arcana': 'arcane tradition', 'tradição arcana': 'arcane tradition', 'arcane tradition': 'arcane tradition', 'arcana tradition': 'arcane tradition', 'estilo de luta': 'fighting style', 'estilo de combate': 'fighting style',

    # Atributos (Ability Scores) - Expansão
    'força': 'strength', 'forca': 'strength', 'for': 'str', 'forç': 'strength', 'força física': 'strength', 'força': 'strength',
    'destreza': 'dexterity', 'dex': 'dex', 'destrza': 'dexterity', 'destre': 'dexterity', 'dexteridade': 'dexterity',
    'constituição': 'constitution', 'constituicao': 'constitution', 'con': 'con', 'const': 'con', 'costituição': 'constitution',
    'inteligência': 'intelligence', 'inteligencia': 'intelligence', 'int': 'int', 'intelig': 'intelligence', 'intelgência': 'intelligence',
    'sabedoria': 'wisdom', 'sab': 'wis', 'sabdoria': 'wisdom', 'sabedria': 'wisdom', 'sbedoria': 'wisdom',
    'carisma': 'charisma', 'car': 'cha', 'crsma': 'charisma', 'charisma': 'charisma', 'carism': 'charisma',
    'atributo': 'ability score', 'atributos': 'ability scores', 'pontos de atributo': 'ability scores',
    'atribto': 'ability score', 'atribut': 'ability score', 'status': 'ability score', 'estatistica': 'ability score', 'estatísticas': 'ability scores',

    # Perícias (Skills) - Expansão
    'acrobacia': 'acrobatics', 'acrobacia': 'acrobatics', 'acrobatismo': 'acrobatics', 'akrobacia': 'acrobatics',
    'arcanismo': 'arcana', 'arcano': 'arcana', 'arcanism': 'arcana', 'arcan': 'arcana', 'arcnismo': 'arcana',
    'atletismo': 'athletics', 'atltismo': 'athletics', 'atletsm': 'athletics', 'atletis': 'athletics',
    'atuação': 'performance', 'atuacao': 'performance', 'atuaçã': 'performance', 'atua': 'performance', 'performace': 'performance',
    'enganção': 'deception', 'enganação': 'deception', 'engnacao': 'deception', 'enganaca': 'deception', 'engano': 'deception',
    'furtividade': 'stealth', 'furtividadi': 'stealth', 'furtvidade': 'stealth', 'furtiv': 'stealth', 'stelth': 'stealth',
    'história': 'history', 'historia': 'history', 'hstória': 'history', 'histor': 'history', 'hist': 'history',
    'intimidação': 'intimidation', 'intimidacao': 'intimidation', 'intimidaçã': 'intimidation', 'intmdacao': 'intimidation',
    'intuição': 'insight', 'intuicao': 'insight', 'intuica': 'insight', 'intuiçã': 'insight', 'instinto': 'insight',
    'investigação': 'investigation', 'investigacao': 'investigation', 'investigaçã': 'investigation', 'invstigacao': 'investigation',
    'lidar com animais': 'animal handling', 'manuseio de animais': 'animal handling', 'lidar animais': 'animal handling', 'trato com animais': 'animal handling',
    'medicina': 'medicine', 'médica': 'medicine', 'medicna': 'medicine', 'medcna': 'medicine',
    'natureza': 'nature', 'naturza': 'nature', 'natura': 'nature', 'natueza': 'nature',
    'percepção': 'perception', 'percepcao': 'perception', 'percepc': 'perception', 'percepçã': 'perception', 'perceção': 'perception',
    'persuasão': 'persuasion', 'persuasao': 'persuasion', 'persuasa': 'persuasion', 'persuasã': 'persuasion', 'persuasion': 'persuasion',
    'prestidigitação': 'sleight of hand', 'prestidigitacao': 'sleight of hand', 'prestidigita': 'sleight of hand',
    'prestidigitação': 'sleight of hand', 'presti': 'sleight of hand',
    'religião': 'religion', 'religiao': 'religion', 'religã': 'religion', 'relgio': 'religion', 'relgiao': 'religion',
    'sobrevivência': 'survival', 'sobrevivencia': 'survival', 'sobreviência': 'survival', 'sobrvivencia': 'survival', 'survivenia': 'survival',
    'perícia': 'skill', 'perícias': 'skills', 'pericia': 'skill', 'percias': 'skills', 'habilidade': 'skill', 'hablidades': 'skills',

    # Combate (Combat) - Expansão
    'iniciativa': 'initiative', 'iniciatva': 'initiative', 'inicativa': 'initiative', 'iniciativa': 'initiative',
    'ação': 'action', 'acao': 'action', 'acões': 'actions', 'acoes': 'actions', 'açã': 'action', 'acão': 'action',
    'ação bônus': 'bonus action', 'acao bonus': 'bonus action', 'açã bônus': 'bonus action', 'bonus acao': 'bonus action',
    'reação': 'reaction', 'reacao': 'reaction', 'reaçã': 'reaction', 'reaca': 'reaction', 'reacão': 'reaction',
    'movimento': 'movement', 'deslocamento': 'speed', 'movmento': 'movement', 'deslocmento': 'speed', 'movi': 'movement',
    'rodada': 'round', 'turno': 'turn', 'rodad': 'round', 'trno': 'turn', 'ronda': 'round',
    'classe de armadura': 'armor class', 'ca': 'ac', 'classe armadura': 'armor class', 'armadura classe': 'armor class', 'c.a': 'ac',
    'pontos de vida': 'hit points', 'pv': 'hp', 'vida': 'hit points', 'pntos de vida': 'hit points', 'vda': 'hit points',
    'dado de vida': 'hit die', 'dados de vida': 'hit dice', 'dado vida': 'hit die', 'dados vida': 'hit dice', 'dado de vida': 'hit die',
    'ataque corpo a corpo': 'melee attack', 'ataque corpo corpo': 'melee attack', 'corpo a corpo': 'melee', 'mele ataque': 'melee attack',
    'ataque à distância': 'ranged attack', 'ataque a distancia': 'ranged attack', 'ataque distancia': 'ranged attack', 'ranged ataque': 'ranged attack',
    'rolagem de ataque': 'attack roll', 'jogada de ataque': 'attack roll', 'rolagem ataque': 'attack roll', 'jogada ataque': 'attack roll',
    'rolagem de dano': 'damage roll', 'jogada de dano': 'damage roll', 'rolagem dano': 'damage roll', 'jogada dano': 'damage roll',
    'ataque de oportunidade': 'opportunity attack', 'ataque oportunidade': 'opportunity attack', 'oportunidade ataque': 'opportunity attack',
    'crítico': 'critical hit', 'critico': 'critical hit', 'acerto crítico': 'critical hit', 'crítco': 'critical hit', 'crit': 'critical hit',
    'surpresa': 'surprise', 'supresa': 'surprise', 'surpreza': 'surprise', 'surprsa': 'surprise',
    'agarrar': 'grapple', 'agarrão': 'grapple', 'agarrao': 'grapple', 'agrar': 'grapple', 'agarrar': 'grapple',
    'empurrar': 'shove', 'empurr': 'shove', 'empurrã': 'shove', 'empurra': 'shove',
    'esquivar': 'dodge', 'esquiva': 'dodge', 'esqivar': 'dodge', 'esqiva': 'dodge',
    'desengajar': 'disengage', 'desengaj': 'disengage', 'desngajar': 'disengage', 'desengaja': 'disengage',
    'ajudar': 'help', 'ajud': 'help', 'ajda': 'help', 'auxiliar': 'help',
    'esconder': 'hide', 'escondr': 'hide', 'esconde': 'hide', 'escoder': 'hide',
    'preparar': 'ready', 'prepar': 'ready', 'prparar': 'ready', 'usar um objeto': 'ready', 'prerar': 'ready',
    'usar um objeto': 'use an object', 'usar objeto': 'use an object', 'usa objeto': 'use an object', 'usar item': 'use an object',
    'lutar com duas armas': 'two-weapon fighting', 'luta duas armas': 'two-weapon fighting', 'duas armas': 'two-weapon fighting', 'dual wield': 'two-weapon fighting',
    'cobertura': 'cover', 'cobrtura': 'cover', 'cobertur': 'cover', 'meia cobertura': 'half cover', 'três quartos cobertura': 'three-quarters cover',
    'ataque desarmado': 'unarmed strike', 'ataque sem arma': 'unarmed strike', 'golpe desarmado': 'unarmed strike',
    'derrubar': 'knockdown', 'derrub': 'knockdown', 'derubar': 'knockdown',
    'flanquear': 'flank', 'flanque': 'flank', 'flanquar': 'flank',
    'teste de resistência': 'saving throw', 'teste de salvamento': 'saving throw', 'salvaguarda': 'saving throw', 'teste salvamento': 'saving throw',
    'ataque furtivo': 'sneak attack', 'ataque surpresa': 'sneak attack', 'furtivo ataque': 'sneak attack', 'sneak ataque': 'sneak attack',
    'mira precisa': 'precise aim', 'mira certa': 'precise aim', 'aim preciso': 'precise aim',
    # Equipamento e Itens (Equipment & Items) - Expansão
    'arma': 'weapon', 'armas': 'weapons', 'rma': 'weapon', 'arm': 'weapon',
    'escudo': 'shield', 'escud': 'shield', 'scudo': 'shield', 'esudo': 'shield',
    'armadura leve': 'light armor', 'armadura leve': 'light armor', 'armdura leve': 'light armor',
    'armadura média': 'medium armor', 'armadura media': 'medium armor', 'armdura média': 'medium armor',
    'armadura pesada': 'heavy armor', 'armadura pesada': 'heavy armor', 'armdura pesada': 'heavy armor',
    'espada': 'sword', 'espada longa': 'longsword', 'espada curta': 'shortsword', 'espa': 'sword', 'espda': 'longsword',
    'machado': 'axe', 'machadinha': 'handaxe', 'machado grande': 'greataxe', 'machdo': 'axe', 'machad': 'handaxe',
    'arco': 'bow', 'arco longo': 'longbow', 'arco curto': 'shortbow', 'arcu': 'bow', 'arrco': 'bow',
    'besta': 'crossbow', 'bsta': 'crossbow', 'best': 'crossbow', 'besta leve': 'light crossbow', 'besta pesada': 'heavy crossbow',
    'adaga': 'dagger', 'adga': 'dagger', 'dagga': 'dagger', 'adaga': 'dagger',
    'mochila': 'backpack', 'mochla': 'backpack', 'mochia': 'backpack', 'mochil': 'backpack',
    'poção': 'potion', 'pção': 'potion', 'poçoes': 'potions', 'pocoes': 'potions', 'poçã': 'potion',
    'poção de cura': 'potion of healing', 'pocão de cura': 'potion of healing', 'poção cura': 'potion of healing',
    'pergaminho': 'scroll', 'pergamno': 'scroll', 'pergamin': 'scroll', 'pergminho': 'scroll',
    'item mágico': 'magic item', 'item magico': 'magic item', 'itens mágicos': 'magic items', 'item máico': 'magic item', 'itemm mágico': 'magic item',
    'ouro': 'gold', 'peças de ouro': 'gold pieces', 'po': 'gp', 'our': 'gold', 'oros': 'gold',
    'prata': 'silver', 'peças de prata': 'silver pieces', 'pp': 'sp', 'prat': 'silver', 'pratas': 'silver',
    'cobre': 'copper', 'peças de cobre': 'copper pieces', 'pc': 'cp', 'cobr': 'copper', 'cobres': 'copper',
    'platina': 'platinum', 'peças de platina': 'platinum pieces', 'pl': 'pp', 'pltina': 'platinum', 'platinum': 'platinum',
    'tocha': 'torch', 'tcha': 'torch', 'torcha': 'torch',
    'corda': 'rope', 'crda': 'rope', 'cord': 'rope',
    'lanterna': 'lantern', 'lantrna': 'lantern', 'lantterna': 'lantern',
    'saco de dormir': 'bedroll', 'saco dormir': 'bedroll', 'saco de dormi': 'bedroll',
    'varinha': 'wand', 'varinha mágica': 'magic wand', 'varnha': 'wand', 'varinha': 'wand',
    'anel': 'ring', 'anl': 'ring', 'aneu': 'ring', 'anel mágico': 'magic ring',
    'amulet': 'amulet', 'amuleto': 'amulet', 'amul': 'amulet', 'amuleto mágico': 'magic amulet',
    'livro de magias': 'spellbook', 'livro de magia': 'spellbook', 'livro magias': 'spellbook', 'spellbok': 'spellbook',
    'componente de magia': 'spell component', 'componente magia': 'spell component', 'compnente de magia': 'spell component',
    'bolsa de componentes': 'component pouch', 'bolsa componentes': 'component pouch', 'bolsa de compnentes': 'component pouch',
    'foco arcano': 'arcane focus', 'foco mágico': 'arcane focus', 'foco arcno': 'arcane focus', 'focu arcano': 'arcane focus',
    'símbolo sagrado': 'holy symbol', 'simbolo sagrado': 'holy symbol', 'símbol sagrado': 'holy symbol',
    'kit de ferramentas': 'tool kit', 'kit ferramentas': 'tool kit', 'kit de ferramntas': 'tool kit',
    'armadilha': 'trap', 'armadila': 'trap', 'armdilha': 'trap', 'trap': 'trap',
    'chave': 'key', 'chve': 'key', 'chav': 'key',
    'baú': 'chest', 'bau': 'chest', 'báu': 'chest', 'bxu': 'chest',
    'gema': 'gem', 'joia': 'gem', 'gma': 'gem', 'gemas': 'gems',
    'artefato': 'artifact', 'artefat': 'artifact', 'artifato': 'artifact', 'artefatto': 'artifact',

    # Magia e Feitiços (Magic & Spells) - Expansão
    'truque': 'cantrip', 'truques': 'cantrips', 'trque': 'cantrip', 'truq': 'cantrip', 'cantrip': 'cantrip',
    'feitiço': 'spell', 'feitiços': 'spells', 'feitico': 'spell', 'feiticos': 'spells', 'feitiç': 'spell', 'feitço': 'spell',
    'nível de magia': 'spell level', 'nivel de magia': 'spell level', 'circulo de magia': 'spell level', 'nivel magia': 'spell level',
    'espaço de magia': 'spell slot', 'espaco de magia': 'spell slot', 'espaço magia': 'spell slot', 'slot de magia': 'spell slot',
    'conjurador': 'spellcaster', 'conjuradores': 'spellcasters', 'conjrador': 'spellcaster', 'conjurdr': 'spellcaster',
    'conjurar': 'cast', 'lançar magia': 'cast a spell', 'conjur': 'cast', 'lançr': 'cast a spell', 'lancar': 'cast',
    'componentes': 'components', 'componente verbal': 'verbal component', 'componente somático': 'somatic component',
    'componente material': 'material component', 'compnentes': 'components', 'component': 'component',
    'duração': 'duration', 'duracao': 'duration', 'duracão': 'duration', 'dur': 'duration', 'duraçã': 'duration',
    'concentração': 'concentration', 'concentracao': 'concentration', 'concetração': 'concentration', 'concentraca': 'concentration',
    'alcance': 'range', 'alcançe': 'range', 'alcnce': 'range', 'alcanc': 'range', 'range': 'range',
    'escola de magia': 'school of magic', 'escola magia': 'school of magic', 'escloa de magia': 'school of magic',
    'abjuração': 'abjuration', 'abjuracao': 'abjuration', 'abjuraçã': 'abjuration', 'abjura': 'abjuration',
    'adivinhação': 'divination', 'adivinhacao': 'divination', 'adivinhaçã': 'divination', 'adivnhação': 'divination',
    'encantamento': 'enchantment', 'encantmento': 'enchantment', 'encntamento': 'enchantment', 'enchant': 'enchantment',
    'evocação': 'evocation', 'evocacao': 'evocation', 'evocaçã': 'evocation', 'evoc': 'evocation',
    'ilusão': 'illusion', 'ilusao': 'illusion', 'ilusa': 'illusion', 'ilusã': 'illusion', 'ilusion': 'illusion',
    'necromancia': 'necromancy', 'necromante': 'necromancer', 'necromncia': 'necromancy', 'necrom': 'necromancy',
    'transmutação': 'transmutation', 'transmutacao': 'transmutation', 'transmutaçã': 'transmutation', 'transmta': 'transmutation',
    'invocação': 'conjuration', 'invocacao': 'conjuration', 'invocaçã': 'conjuration', 'invoc': 'conjuration',
    'ritual': 'ritual', 'ritualístico': 'ritual', 'ritul': 'ritual', 'ritua': 'ritual',
    'magia divina': 'divine magic', 'magia divna': 'divine magic', 'divna magia': 'divine magic',
    'magia arcana': 'arcane magic', 'magia arcna': 'arcane magic', 'arcna magia': 'arcane magic',
    'magia de área': 'area of effect', 'magia area': 'area of effect', 'magia de área': 'area of effect', 'aoe': 'area of effect',
    'feitiço de dano': 'damage spell', 'feitico de dano': 'damage spell', 'magia de dano': 'damage spell',
    'feitiço de cura': 'healing spell', 'feitico de cura': 'healing spell', 'magia de cura': 'healing spell',
    'feitiço de controle': 'control spell', 'feitico de controle': 'control spell', 'magia de controle': 'control spell',
    'míssil mágico': 'magic missile', 'missil magico': 'magic missile', 'míssil máico': 'magic missile',
    'bola de fogo': 'fireball', 'bola fogo': 'fireball', 'firebal': 'fireball',
    'cura ferimentos': 'cure wounds', 'cura feriment': 'cure wounds', 'curar ferimentos': 'cure wounds',
    'escudo arcano': 'shield', 'escudo arcan': 'shield', 'escudo mágic': 'shield',
    'invisibilidade': 'invisibility', 'invisibilidadi': 'invisibility', 'invisiblidade': 'invisibility',
    'polimorfia': 'polymorph', 'polimorfa': 'polymorph', 'polimrfia': 'polymorph',
    'desejo': 'wish', 'desjo': 'wish', 'wish': 'wish',
    'contramágica': 'counterspell', 'contramagica': 'counterspell', 'contra-mágica': 'counterspell', 'counter spell': 'counterspell',
    'teletransporte': 'teleport', 'teletransprt': 'teleport', 'teleporte': 'teleport',
    'barreira mágica': 'magic barrier', 'barreira magica': 'magic barrier', 'barreira máica': 'magic barrier',
    'detecção de magia': 'detect magic', 'detecao de magia': 'detect magic', 'detectar magia': 'detect magic',
    'identificar': 'identify', 'identificr': 'identify', 'identifica': 'identify',
    'levitação': 'levitate', 'levitacao': 'levitate', 'levitaçã': 'levitate', 'levitar': 'levitate',
    'luz': 'light', 'luz mágica': 'light', 'luz magica': 'light',
    'trevas': 'darkness', 'trvas': 'darkness', 'treva': 'darkness',
    'sono': 'sleep', 'son': 'sleep', 'sno': 'sleep',
    'paralisar': 'hold person', 'paralizar': 'hold person', 'paralisa': 'hold person',
    'sugestão': 'suggestion', 'sugestao': 'suggestion', 'sugestã': 'suggestion',
    'raio de gelo': 'ray of frost', 'raio gelo': 'ray of frost', 'ray of frst': 'ray of frost',
    'mão arcana': 'arcane hand', 'mao arcana': 'arcane hand', 'mão mágica': 'arcane hand',
    'muralha de força': 'wall of force', 'muralha forca': 'wall of force', 'muralha de força': 'wall of force',

    # Condições (Conditions) - Expansão
    'agarrado': 'grappled', 'agarado': 'grappled', 'agrrado': 'grappled', 'agarrad': 'grappled',
    'amedrontado': 'frightened', 'amedrontdo': 'frightened', 'amedontado': 'frightened', 'assustado': 'frightened',
    'atordoado': 'stunned', 'atordado': 'stunned', 'atrdado': 'stunned', 'atordo': 'stunned',
    'caído': 'prone', 'deitado': 'prone', 'caido': 'prone', 'cído': 'prone', 'deitad': 'prone',
    'cego': 'blinded', 'cgo': 'blinded', 'ceg': 'blinded', 'cegu': 'blinded',
    'contido': 'restrained', 'cntido': 'restrained', 'contdo': 'restrained', 'contid': 'restrained',
    'enfeitiçado': 'charmed', 'enfeiticado': 'charmed', 'enfeitçado': 'charmed', 'enfetçado': 'charmed', 'charmado': 'charmed',
    'envenenado': 'poisoned', 'envennado': 'poisoned', 'envnenado': 'poisoned', 'envenenad': 'poisoned',
    'exausto': 'exhausted', 'exaustão': 'exhaustion', 'exaustao': 'exhaustion', 'exasto': 'exhausted', 'exaust': 'exhausted',
    'incapacitado': 'incapacitated', 'incapcitado': 'incapacitated', 'incapacitad': 'incapacitated', 'incpacitado': 'incapacitated',
    'inconsciente': 'unconscious', 'inconscente': 'unconscious', 'inconsiente': 'unconscious', 'inconsc': 'unconscious',
    'invisível': 'invisible', 'invisivel': 'invisible', 'invisíel': 'invisible', 'invisivl': 'invisible',
    'paralisado': 'paralyzed', 'paralizado': 'paralyzed', 'pralisado': 'paralyzed', 'paralisad': 'paralyzed',
    'petrificado': 'petrified', 'petrificad': 'petrified', 'petrficado': 'petrified', 'petrificado': 'petrified',
    'surdo': 'deafened', 'srdo': 'deafened', 'sur': 'deafened', 'surd': 'deafened',
    'confuso': 'confused', 'confso': 'confused', 'cnfuso': 'confused', 'confusion': 'confused',
    'enfraquecido': 'weakened', 'enfraquecido': 'weakened', 'enfrquecido': 'weakened', 'enfraquecid': 'weakened',
    'lentidão': 'slowed', 'lentidao': 'slowed', 'lentidão': 'slowed', 'lntidão': 'slowed',

    # Monstros (Monsters) - Expansão
    'monstro': 'monster', 'monstros': 'monsters', 'mnstro': 'monster', 'monstr': 'monster',
    'criatura': 'creature', 'criaturas': 'creatures', 'criatua': 'creature', 'criatur': 'creature',
    'besta': 'beast', 'bst': 'beast', 'best': 'beast', 'besta feroz': 'beast',
    'dragão': 'dragon', 'dragao': 'dragon', 'dragoes': 'dragons', 'drgão': 'dragon', 'dragõ': 'dragon',
    'beholder': 'beholder', 'observador': 'beholder', 'beholdr': 'beholder', 'bholder': 'beholder',
    'devorador de mentes': 'mind flayer', 'illithid': 'illithid', 'devorador mentes': 'mind flayer', 'mindflayer': 'mind flayer',
    'lich': 'lich', 'lch': 'lich', 'lih': 'lich',
    'morto-vivo': 'undead', 'morto vivo': 'undead', 'mortovivo': 'undead', 'mrt-vivo': 'undead',
    'zumbi': 'zombie', 'zumbis': 'zombies', 'zubi': 'zombie', 'zmb': 'zombie',
    'esqueleto': 'skeleton', 'esqeleto': 'skeleton', 'esqleto': 'skeleton', 'skleton': 'skeleton',
    'vampiro': 'vampire', 'vmpiro': 'vampire', 'vampir': 'vampire', 'vamp': 'vampire',
    'lobisomem': 'werewolf', 'lobisomen': 'werewolf', 'lobisom': 'werewolf', 'werewlf': 'werewolf',
    'elemental': 'elemental', 'elemntal': 'elemental', 'elementl': 'elemental',
    'elemental de fogo': 'fire elemental', 'elemental fogo': 'fire elemental', 'fire elementl': 'fire elemental',
    'elemental de água': 'water elemental', 'elemental agua': 'water elemental', 'water elementl': 'water elemental',
    'elemental de ar': 'air elemental', 'elemental ar': 'air elemental', 'air elementl': 'air elemental',
    'elemental de terra': 'earth elemental', 'elemental terra': 'earth elemental', 'earth elementl': 'earth elemental',
    'demônio': 'demon', 'demonio': 'demon', 'demnio': 'demon', 'demon': 'demon',
    'diabo': 'devil', 'diab': 'devil', 'dvabo': 'devil', 'devil': 'devil',
    'golem': 'golem', 'golme': 'golem', 'gole': 'golem',
    'golem de ferro': 'iron golem', 'golem ferro': 'iron golem', 'iron golm': 'iron golem',
    'golem de carne': 'flesh golem', 'golem carne': 'flesh golem', 'flesh golm': 'flesh golem',
    'tarrasque': 'tarrasque', 'tarrsque': 'tarrasque', 'tarasque': 'tarrasque',
    'hidra': 'hydra', 'hdra': 'hydra', 'hyda': 'hydra',
    'quimera': 'chimera', 'qimera': 'chimera', 'chmera': 'chimera',
    'basilisco': 'basilisk', 'basilsco': 'basilisk', 'basilsk': 'basilisk',
    'medusa': 'medusa', 'mdusa': 'medusa', 'medsa': 'medusa',
    'manticora': 'manticore', 'mantcora': 'manticore', 'manticra': 'manticore',
    'wyvern': 'wyvern', 'wvern': 'wyvern', 'wyvrn': 'wyvern',
    'troll': 'troll', 'trol': 'troll', 'trll': 'troll',
    'ogro': 'ogre', 'ogr': 'ogre', 'ogro': 'ogre',
    'gigante': 'giant', 'gigant': 'giant', 'giante': 'giant',
    'gigante das colinas': 'hill giant', 'gigante colinas': 'hill giant', 'hill gaint': 'hill giant',
    'gigante de pedra': 'stone giant', 'gigante pedra': 'stone giant', 'stone gaint': 'stone giant',
    'gigante de fogo': 'fire giant', 'gigante fogo': 'fire giant', 'fire gaint': 'fire giant',
    'gigante de gelo': 'frost giant', 'gigante gelo': 'frost giant', 'frost gaint': 'frost giant',
    'gigante das nuvens': 'cloud giant', 'gigante nuvens': 'cloud giant', 'cloud gaint': 'cloud giant',
    'gigante da tempestade': 'storm giant', 'gigante tempestade': 'storm giant', 'storm gaint': 'storm giant',
    'fada': 'fey', 'fda': 'fey', 'fay': 'fey',
    'pixie': 'pixie', 'pxie': 'pixie', 'pixi': 'pixie',
    'sprite': 'sprite', 'sprte': 'sprite', 'sprit': 'sprite',
    'gnoll': 'gnoll', 'gnol': 'gnoll', 'gnll': 'gnoll',
    'sátiro': 'satyr', 'satiro': 'satyr', 'satrio': 'satyr',
    'harpia': 'harpy', 'hrpia': 'harpy', 'hapry': 'harpy',
    'grifo': 'griffon', 'grfo': 'griffon', 'griffn': 'griffon',
    'hipogrifo': 'hippogriff', 'hipogrif': 'hippogriff', 'hippogrif': 'hippogriff',
    'esfinge': 'sphinx', 'esfnge': 'sphinx', 'sphnx': 'sphinx',
    'dracolich': 'dracolich', 'draclich': 'dracolich', 'dracolch': 'dracolich',
    'aboleth': 'aboleth', 'abolth': 'aboleth', 'aboleh': 'aboleth',
    'kraken': 'kraken', 'krakn': 'kraken', 'kraken': 'kraken',
    'roc': 'roc', 'rc': 'roc', 'rok': 'roc',
    'unicornio': 'unicorn', 'unicórnio': 'unicorn', 'unicrnio': 'unicorn', 'unicorn': 'unicorn',
    'pegaso': 'pegasus', 'pegso': 'pegasus', 'pegasus': 'pegasus',
    'lobo atroz': 'dire wolf', 'lobo atros': 'dire wolf', 'dire wlf': 'dire wolf',
    'urso atroz': 'dire bear', 'urso atros': 'dire bear', 'dire br': 'dire bear',
    'doppelganger': 'doppelganger', 'dopelganger': 'doppelganger', 'doppelgngr': 'doppelganger',
    'shadow': 'shadow', 'sombra': 'shadow', 'shdow': 'shadow',
    'wraith': 'wraith', 'wrath': 'wraith', 'wraih': 'wraith',
    'specter': 'specter', 'espectro': 'specter', 'spcter': 'specter',
    'banshee': 'banshee', 'banshe': 'banshee', 'banshe': 'banshee',
    'ghoul': 'ghoul', 'ghul': 'ghoul', 'ghol': 'ghoul',
    'ghast': 'ghast', 'ghst': 'ghast', 'gast': 'ghast',
    'wight': 'wight', 'wght': 'wight', 'wigth': 'wight',
    'revenant': 'revenant', 'revnant': 'revenant', 'revennt': 'revenant',
    'naga': 'naga', 'nga': 'naga', 'naga': 'naga',
    'lamia': 'lamia', 'lmia': 'lamia', 'lamia': 'lamia',
    'succubus': 'succubus', 'sucubus': 'succubus', 'succubs': 'succubus',
    'incubus': 'incubus', 'incbus': 'incubus', 'incubs': 'incubus',
    'rakshasa': 'rakshasa', 'raksasa': 'rakshasa', 'rakshsa': 'rakshasa',
    'oni': 'oni', 'on': 'oni', 'oni': 'oni',
    'yeti': 'yeti', 'yti': 'yeti', 'yeti': 'yeti',
    'ettin': 'ettin', 'etin': 'ettin', 'ettin': 'ettin',
    'cyclope': 'cyclops', 'cclope': 'cyclops', 'cyclps': 'cyclops',
    'treant': 'treant', 'trant': 'treant', 'trean': 'treant',
    'dryad': 'dryad', 'dryd': 'dryad', 'driad': 'dryad',
    'shambling mound': 'shambling mound', 'shambling mnd': 'shambling mound', 'shamblng mound': 'shambling mound',
    'will-o-wisp': 'will-o-wisp', 'willowisp': 'will-o-wisp',
    'mimic': 'mimic', 'mmic': 'mimic', 'mimc': 'mimic',
    'rust monster': 'rust monster', 'rust monstr': 'rust monster', 'rst monster': 'rust monster',
    'gelatinous cube': 'gelatinous cube', 'gelatinous cub': 'gelatinous cube', 'gelatnous cube': 'gelatinous cube',
    'ochre jelly': 'ochre jelly', 'ochre jely': 'ochre jelly', 'ochr jelly': 'ochre jelly',
    'black pudding': 'black pudding', 'blck pudding': 'black pudding', 'black puding': 'black pudding',
    'slime': 'slime', 'slme': 'slime', 'slime': 'slime',
    'ooze': 'ooze', 'oze': 'ooze', 'ooze': 'ooze',
    'gargoyle': 'gargoyle', 'grgoyle': 'gargoyle', 'gargyle': 'gargoyle',
    'hell hound': 'hell hound', 'hell hnd': 'hell hound', 'hel hound': 'hell hound',
    'nightmare': 'nightmare', 'nghtmare': 'nightmare', 'nightmre': 'nightmare',
    'salamander': 'salamander', 'salmander': 'salamander', 'salamandr': 'salamander',
    'efreeti': 'efreeti', 'efreti': 'efreeti', 'efreet': 'efreeti',
    'djinn': 'djinn', 'djin': 'djinn', 'djinn': 'djinn',
    'marid': 'marid', 'mrid': 'marid', 'marid': 'marid',
    'dao': 'dao', 'do': 'dao', 'dao': 'dao',
    'couatl': 'couatl', 'cuatl': 'couatl', 'coutl': 'couatl',
    'ki-rin': 'ki-rin', 'kirin': 'ki-rin', 'ki-rn': 'ki-rin',
    'androsfinge': 'androsphinx', 'androsfnge': 'androsphinx', 'andrsphinx': 'androsphinx',
    'giroesfinge': 'gynosphinx', 'giroesfnge': 'gynosphinx', 'gyrsphinx': 'gynosphinx',
    'remorhaz': 'remorhaz', 'rmorhaz': 'remorhaz', 'remorhz': 'remorhaz',
    'roper': 'roper', 'rper': 'roper', 'ropr': 'roper',
    'sahuagin': 'sahuagin', 'sahagin': 'sahuagin', 'sahuagn': 'sahuagin',
    'sea hag': 'sea hag', 'sea hge': 'sea hag', 'se hag': 'sea hag',
    'green hag': 'green hag', 'grn hag': 'green hag', 'green hge': 'green hag',
    'night hag': 'night hag', 'nght hag': 'night hag', 'night hge': 'night hag',
    'bone naga': 'bone naga', 'bne naga': 'bone naga', 'bone nga': 'bone naga',
    'spirit naga': 'spirit naga', 'sprt naga': 'spirit naga', 'spirit nga': 'spirit naga',
    'guardian naga': 'guardian naga', 'gardian naga': 'guardian naga', 'guardan naga': 'guardian naga',
    'chuul': 'chuul', 'chul': 'chuul', 'chuul': 'chuul',
    'umber hulk': 'umber hulk', 'umbr hulk': 'umber hulk', 'umber hlk': 'umber hulk',
    'xorn': 'xorn', 'xrn': 'xorn', 'xorn': 'xorn',
    'otyugh': 'otyugh', 'otygh': 'otyugh', 'otugh': 'otyugh',
    'neo-otyugh': 'neo-otyugh', 'neo-otygh': 'neo-otyugh', 'neo-otugh': 'neo-otyugh',
    'behir': 'behir', 'bhir': 'behir', 'behir': 'behir',
    'ankheg': 'ankheg', 'nkheg': 'ankheg', 'ankhg': 'ankheg',
    'bulette': 'bulette', 'bulete': 'bulette', 'bulett': 'bulette',
    'carrion crawler': 'carrion crawler', 'crrion crawler': 'carrion crawler', 'carrion crwler': 'carrion crawler',
    'darkmantle': 'darkmantle', 'drkmantle': 'darkmantle', 'darkmntle': 'darkmantle',
    'flumph': 'flumph', 'flmph': 'flumph', 'flumh': 'flumph',
    'gibbering mouther': 'gibbering mouther', 'gbbering mouther': 'gibbering mouther', 'gibbring mouther': 'gibbering mouther',
    'grell': 'grell', 'grll': 'grell', 'grell': 'grell',
    'hook horror': 'hook horror', 'hok horror': 'hook horror', 'hook hrror': 'hook horror',
    'kuo-toa': 'kuo-toa', 'kuotoa': 'kuo-toa', 'kuo-ta': 'kuo-toa',
    'merrow': 'merrow', 'mrrow': 'merrow', 'merow': 'merrow',
    'myconid': 'myconid', 'myconid': 'myconid', 'myconid': 'myconid',
    'piercer': 'piercer', 'prcer': 'piercer', 'piercr': 'piercer',
    'purple worm': 'purple worm', 'prple worm': 'purple worm', 'purple wrm': 'purple worm',
    'rust monster': 'rust monster', 'rst monster': 'rust monster', 'rust monstr': 'rust monster',
    'shambling mound': 'shambling mound', 'shamblng mound': 'shambling mound', 'shambling mnd': 'shambling mound',
    'slaad': 'slaad', 'slad': 'slaad', 'slaad': 'slaad',
    'red slaad': 'red slaad', 'rd slaad': 'red slaad', 'red slad': 'red slaad',
    'blue slaad': 'blue slaad', 'blu slaad': 'blue slaad', 'blue slad': 'blue slaad',
    'green slaad': 'green slaad', 'grn slaad': 'green slaad', 'green slad': 'green slaad',
    'gray slaad': 'gray slaad', 'gry slaad': 'gray slaad', 'gray slad': 'gray slaad',
    'death slaad': 'death slaad', 'deth slaad': 'death slaad', 'death slad': 'death slaad',
    'troglodyte': 'troglodyte', 'trglodyte': 'troglodyte', 'troglodyt': 'troglodyte',
    'yugoloth': 'yugoloth', 'yugloth': 'yugoloth', 'yugolth': 'yugoloth',
    'mezzoloth': 'mezzoloth', 'mzzoloth': 'mezzoloth', 'mezzloth': 'mezzoloth',
    'nycaloth': 'nycaloth', 'nycloth': 'nycaloth', 'nycaloth': 'nycaloth',
    'ultroloth': 'ultroloth', 'ultrloth': 'ultroloth', 'ultrolth': 'ultroloth',
    'arcanaloth': 'arcanaloth', 'rcanaloth': 'arcanaloth', 'arcanloth': 'arcanaloth',
    'modron': 'modron', 'mdron': 'modron', 'modrn': 'modron',
    'monodrone': 'monodrone', 'mnodrone': 'monodrone', 'monodrne': 'monodrone',
    'duodrone': 'duodrone', 'dodrone': 'duodrone', 'duodrne': 'duodrone',
    'tridrone': 'tridrone', 'trdrone': 'tridrone', 'tridrne': 'tridrone',
    'quadrone': 'quadrone', 'qadrone': 'quadrone', 'quadrane': 'quadrone',
    'pentadrone': 'pentadrone', 'pntadrone': 'pentadrone', 'pentadrne': 'pentadrone',
    'inevitable': 'inevitable', 'invitable': 'inevitable', 'inevitble': 'inevitable',
    'marut': 'marut', 'mrut': 'marut', 'marut': 'marut',
    'kolyarut': 'kolyarut', 'klyarut': 'kolyarut', 'kolyart': 'kolyarut',
    'zariel': 'zariel', 'zriel': 'zariel', 'zariel': 'zariel',
    'asmodeus': 'asmodeus', 'asmodus': 'asmodeus', 'asmodes': 'asmodeus',
    'baalzebul': 'baalzebul', 'balzebul': 'baalzebul', 'baalzbul': 'baalzebul',
    'belial': 'belial', 'blial': 'belial', 'belial': 'belial',
    'dispater': 'dispater', 'dspater': 'dispater', 'dispatr': 'dispater',
    'fierna': 'fierna', 'frna': 'fierna', 'fiern': 'fierna',
    'glasya': 'glasya', 'glsya': 'glasya', 'glasy': 'glasya',
    'levistus': 'levistus', 'lvistus': 'levistus', 'levists': 'levistus',
    'malphas': 'malphas', 'mlphas': 'malphas', 'malphs': 'malphas',
    'mephistopheles': 'mephistopheles', 'mephistpeles': 'mephistopheles', 'mephistophles': 'mephistopheles',
    'zariel': 'zariel', 'zriel': 'zariel', 'zariel': 'zariel',
    'orcus': 'orcus', 'orcs': 'orcus', 'orcus': 'orcus',
    'demogorgon': 'demogorgon', 'demgorgon': 'demogorgon', 'demogrgon': 'demogorgon',
    'yeenoghu': 'yeenoghu', 'ynoghu': 'yeenoghu', 'yeenghu': 'yeenoghu',
    'baphomet': 'baphomet', 'bphomet': 'baphomet', 'baphomt': 'baphomet',
    'juiblex': 'juiblex', 'jiblex': 'juiblex', 'juiblx': 'juiblex',
    'zuggtmoy': 'zuggtmoy', 'zggtmoy': 'zuggtmoy', 'zuggtmy': 'zuggtmoy',
    'lolth': 'lolth', 'loth': 'lolth', 'lolth': 'lolth',
    'tiamat': 'tiamat', 'tamat': 'tiamat', 'tiamt': 'tiamat',
    'bahamut': 'bahamut', 'bhamut': 'bahamut', 'bahamt': 'bahamut',
    'archdevil': 'archdevil', 'archdevl': 'archdevil', 'archdvil': 'archdevil',
    'demon lord': 'demon lord', 'demon lrd': 'demon lord', 'dmon lord': 'demon lord',
    'elder elemental': 'elder elemental', 'eldr elemental': 'elder elemental', 'elder elementl': 'elder elemental',
    'phoenix': 'phoenix', 'phnix': 'phoenix', 'phoenx': 'phoenix',
    'leviathan': 'leviathan', 'lviathan': 'leviathan', 'levithan': 'leviathan',
    'zaratan': 'zaratan', 'zratan': 'zaratan', 'zartan': 'zaratan',
    'astral dreadnought': 'astral dreadnought', 'astrl dreadnought': 'astral dreadnought', 'astral drednought': 'astral dreadnought',
    'empyrean': 'empyrean', 'empyran': 'empyrean', 'empirean': 'empyrean',
    'solar': 'solar', 'slar': 'solar', 'sola': 'solar',
    'planetary': 'planetary', 'planetry': 'planetary', 'planetar': 'planetary',
    'deva': 'deva', 'dva': 'deva', 'deva': 'deva',
    'titan': 'titan', 'ttan': 'titan', 'titan': 'titan',
    'elder brain': 'elder brain', 'eldr brain': 'elder brain', 'elder bran': 'elder brain',
    'mind flayer': 'mind flayer', 'mnd flayer': 'mind flayer', 'mind flayr': 'mind flayer',
    'ulitharid': 'ulitharid', 'ultharid': 'ulitharid', 'ulithrid': 'ulitharid',
    'cerberus': 'cerberus', 'crberus': 'cerberus', 'cerbrus': 'cerberus',
    'hydra': 'hydra', 'hdra': 'hydra', 'hydra': 'hydra',
    'chimera': 'chimera', 'chmera': 'chimera', 'chimra': 'chimera',
    'gorgon': 'gorgon', 'grgon': 'gorgon', 'gorgn': 'gorgon',
    'cockatrice': 'cockatrice', 'cckatrice': 'cockatrice', 'cockatric': 'cockatrice',
    'lamia': 'lamia', 'lmia': 'lamia', 'lamia': 'lamia',
    'medusa': 'medusa', 'mdusa': 'medusa', 'medsa': 'medusa',
    'naga': 'naga', 'nga': 'naga', 'naga': 'naga',
    'sphinx': 'sphinx', 'sphnx': 'sphinx', 'spinx': 'sphinx',
    'unicorn': 'unicorn', 'unicrn': 'unicorn', 'unicor': 'unicorn',
    'pegasus': 'pegasus', 'pgasus': 'pegasus', 'pegasus': 'pegasus',
    'griffon': 'griffon', 'grffon': 'griffon', 'griffn': 'griffon',
    'hippogriff': 'hippogriff', 'hppogriff': 'hippogriff', 'hippogrif': 'hippogriff',
    'manticore': 'manticore', 'mnticore': 'manticore', 'manticor': 'manticore',
    'wyvern': 'wyvern', 'wvern': 'wyvern', 'wyvrn': 'wyvern',
    'dragon turtle': 'dragon turtle', 'drgon turtle': 'dragon turtle', 'dragon trtle': 'dragon turtle',
    'pseudodragon': 'pseudodragon', 'psudodragon': 'pseudodragon', 'pseudodrag': 'pseudodragon',
    'faerie dragon': 'faerie dragon', 'farie dragon': 'faerie dragon', 'faerie drgon': 'faerie dragon',
    'shadow dragon': 'shadow dragon', 'shdow dragon': 'shadow dragon', 'shadow drgon': 'shadow dragon',
    'dracolich': 'dracolich', 'draclich': 'dracolich', 'dracolch': 'dracolich',
    'ghost': 'ghost', 'ghst': 'ghost', 'gost': 'ghost',
    'specter': 'specter', 'spcter': 'specter', 'spectr': 'specter',
    'wraith': 'wraith', 'wrath': 'wraith', 'wraih': 'wraith',
    'banshee': 'banshee', 'bnhee': 'banshee', 'banshe': 'banshee',
    'shadow': 'shadow', 'shdow': 'shadow', 'shado': 'shadow',
    'zombie': 'zombie', 'zmbie': 'zombie', 'zombi': 'zombie',
    'skeleton': 'skeleton', 'skleton': 'skeleton', 'skeletn': 'skeleton',
    'ghoul': 'ghoul', 'ghul': 'ghoul', 'ghol': 'ghoul',
    'ghast': 'ghast', 'ghst': 'ghast', 'gast': 'ghast',
    'wight': 'wight', 'wght': 'wight', 'wigth': 'wight',
    'revenant': 'revenant', 'rvnant': 'revenant', 'revennt': 'revenant',
    'vampire': 'vampire', 'vmpire': 'vampire', 'vampir': 'vampire',
    'vampire spawn': 'vampire spawn', 'vmpire spawn': 'vampire spawn', 'vampire spwn': 'vampire spawn',
    'lich': 'lich', 'lch': 'lich', 'lih': 'lich',
    'demilich': 'demilich', 'dmilich': 'demilich', 'demilch': 'demilich',
    'death knight': 'death knight', 'deth knight': 'death knight', 'death knght': 'death knight',
    'death tyrant': 'death tyrant', 'deth tyrant': 'death tyrant', 'death tyrnt': 'death tyrant',
    'beholder': 'beholder', 'bholder': 'beholder', 'beholdr': 'beholder',
    'spectator': 'spectator', 'spctator': 'spectator', 'spectatr': 'spectator',
    'gazer': 'gazer', 'gzr': 'gazer', 'gazr': 'gazer',
    'mind flayer': 'mind flayer', 'mnd flayer': 'mind flayer', 'mind flayr': 'mind flayer',
    'ulitharid': 'ulitharid', 'ultharid': 'ulitharid', 'ulithrid': 'ulitharid',
    'elder brain': 'elder brain', 'eldr brain': 'elder brain', 'elder bran': 'elder brain',
    'aboleth': 'aboleth', 'abolth': 'aboleth', 'aboleh': 'aboleth',
    'kraken': 'kraken', 'krakn': 'kraken', 'kraken': 'kraken',
    'chuul': 'chuul', 'chul': 'chuul', 'chuul': 'chuul',
    'gibbering mouther': 'gibbering mouther', 'gbbering mouther': 'gibbering mouther', 'gibbring mouther': 'gibbering mouther',
    'otyugh': 'otyugh', 'otugh': 'otyugh', 'otygh': 'otyugh',
    'neo-otyugh': 'neo-otyugh', 'neo-otugh': 'neo-otyugh', 'neo-otygh': 'neo-otyugh',
    'umber hulk': 'umber hulk', 'umbr hulk': 'umber hulk', 'umber hlk': 'umber hulk',
    'xorn': 'xorn', 'xrn': 'xorn', 'xorn': 'xorn',
    'grell': 'grell', 'grll': 'grell', 'grell': 'grell',
    'hook horror': 'hook horror', 'hok horror': 'hook horror', 'hook hrror': 'hook horror',
    'darkmantle': 'darkmantle', 'drkmantle': 'darkmantle', 'darkmntle': 'darkmantle',
    'carrion crawler': 'carrion crawler', 'crrion crawler': 'carrion crawler', 'carrion crwler': 'carrion crawler',
    'ankheg': 'ankheg', 'nkheg': 'ankheg', 'ankhg': 'ankheg',
    'bulette': 'bulette', 'bulete': 'bulette', 'bulett': 'bulette',
    'purple worm': 'purple worm', 'prple worm': 'purple worm', 'purple wrm': 'purple worm',
    'remorhaz': 'remorhaz', 'rmorhaz': 'remorhaz', 'remorhz': 'remorhaz',
    'roper': 'roper', 'rper': 'roper', 'ropr': 'roper',
    'rust monster': 'rust monster', 'rst monster': 'rust monster', 'rust monstr': 'rust monster',
    'shambling mound': 'shambling mound', 'shamblng mound': 'shambling mound', 'shambling mnd': 'shambling mound',
    'treant': 'treant', 'trant': 'treant', 'trean': 'treant',
    'dryad': 'dryad', 'driad': 'dryad', 'dryd': 'dryad',
    'will-o-wisp': 'will-o-wisp', 'willowisp': 'will-o-wisp',
    'mimic': 'mimic', 'mmic': 'mimic', 'mimc': 'mimic',
    'gelatinous cube': 'gelatinous cube', 'gelatinous cub': 'gelatinous cube', 'gelatnous cube': 'gelatinous cube',
    'ochre jelly': 'ochre jelly', 'ochre jely': 'ochre jelly', 'ochr jelly': 'ochre jelly',
    'black pudding': 'black pudding', 'blck pudding': 'black pudding', 'black puding': 'black pudding',
    'slime': 'slime', 'slme': 'slime', 'slime': 'slime',
    'ooze': 'ooze', 'oze': 'ooze', 'ooze': 'ooze',
    'gargoyle': 'gargoyle', 'grgoyle': 'gargoyle', 'gargyle': 'gargoyle',
    'hell hound': 'hell hound', 'hel hound': 'hell hound', 'hell hnd': 'hell hound',
    'nightmare': 'nightmare', 'nghtmare': 'nightmare', 'nightmre': 'nightmare',
    'salamander': 'salamander', 'salmander': 'salamander', 'salamandr': 'salamander',
    'efreeti': 'efreeti', 'efreti': 'efreeti', 'efreet': 'efreeti',
    'djinn': 'djinn', 'djin': 'djinn', 'djinn': 'djinn',
    'marid': 'marid', 'mrid': 'marid', 'marid': 'marid',
    'dao': 'dao', 'do': 'dao', 'dao': 'dao',
    'couatl': 'couatl', 'cuatl': 'couatl', 'coutl': 'couatl',
    'ki-rin': 'ki-rin', 'kirin': 'ki-rin', 'ki-rn': 'ki-rin',
    'androsfinge': 'androsphinx' 
    }